version: '3.7'

services:
  app:
    # image: whatwewant/gztinypng:v0.0.6
    build:
      context: .
    ports:
      - 0.0.0.0:6666:6666
    # command: sleep infinity
    volumes:
      - ./conf:/conf
